### PR TITLE
Add missing DOM classes

### PR DESCRIPTION
**Pull request by PedroAmorim**
Hi Andres!

I catch this error:
Uncaught Error: Call to undefined method DOMEntityReference::getAttribute() in vendor/andreskrey/readability.php/src/Readability.php:528

When parse [www.lemonde.fr](http://www.lemonde.fr/idees/article/2011/06/20/la-crise-europeenne-est-une-crise-de-la-dette-pas-de-l-euro_1538337_3232.html) with config:

> $config->setWordThreshold(100)  
->setSummonCthulhu(true) 
->setFixRelativeURLs(true)  
->setOriginalURL($url);  

After some investigations seem to be caused by a missing class on the DOM's overwrite classes.

Maybe should I add DOMEntity too?

### CODE REVIEW

**Comment by andreskrey** [comment]
That's great! 

Would you mind adding a test case? I tried to parse http://www.lemonde.fr/societe/article/2018/01/10/a-l-hopital-saint-louis-le-recours-a-l-ambulatoire-oblige-a-etre-plus-efficient_5239864_3224.html but no error was raised.

**Comment by andreskrey** [comment]
Oh! and you also need to declare it in https://github.com/andreskrey/readability.php/blob/master/src/Nodes/DOM/DOMDocument.php

**Comment by PedroAmorim** [comment]
Sorry I have hidden the link for more readability.
Here the full link:
http://www.lemonde.fr/idees/article/2011/06/20/la-crise-europeenne-est-une-crise-de-la-dette-pas-de-l-euro_1538337_3232.html

**Comment by andreskrey** [comment]
Ah! Sorry about that.

Thanks for the test :D

**Pull request merged**
