### PR TITLE
bugfixing

### PR DESCRIPTION
**Pull request by jagermesh**
Some methods return NULL or FALSE, so following request to them as objects fail

### CODE REVIEW

**Comment by andreskrey** [comment]
Hi @jagermesh, thanks for the PR

Would you mind addressing the issues from StyleCI? Also, seems that you made some changes to the indentation (probably switched from spaces to tabs, or somethign like that) because the diff show changes on lines that seems to be the same.


Thanks!

**Comment by jagermesh** [comment]
Please check! Sorry for troubles!

**Comment by andreskrey** [comment]
Hi @jagermesh I've been inspecting your code and I'm not sure if the best approach is to surround everything in if statements. Would you mind providing HTMLs where the methods return null or false? Maybe we can approach this issue in a different, more clean way.

Thanks!

**Comment by jagermesh** [comment]
Ok! Unfortunately I don't have that html stored anywhere :( I'll rollback changes and will monitor project for same errors. Will let you know shortly.

**Comment by andreskrey** [comment]
Great, thanks!

**Comment by jagermesh** [comment]
Sorry for delay, here is the example. 

Page downloaded from http://jdan.github.io/cleaver/ using Guzzle

```
    $client = new GuzzleHttp\Client();
    $cookieJar = new \GuzzleHttp\Cookie\CookieJar();

    $response = $client->request( 'GET'
                                , $url
                                , array( 'headers'         => array( 'User-Agent' => 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.98 Safari/537.36'
                                                                   , 'Accept'     => 'text/html, application/xhtml+xml, application/xml, application/json, text/plain, */*'
                                                                   )
                                       , 'cookies'         => $cookieJar
                                       , 'timeout'         => 60
                                       , 'connect_timeout' => 15
                                       )
                                );

```

Page

[0.html.zip](https://github.com/andreskrey/readability.php/files/963366/0.html.zip)

Errors

```
Notice: Trying to get property of non-object
    in /Users/jagermesh/www/reviewlater/vendor/andreskrey/readability.php/src/HTMLParser.php, line 147
```

```
[FATAL] Error: Argument 1 passed to andreskrey\Readability\Readability::__construct() must be an instance of DOMNode, null given, called in /Users/jagermesh/www/reviewlater/vendor/andreskrey/readability.php/src/HTMLParser.php on line 147
    in /Users/jagermesh/www/reviewlater/vendor/andreskrey/readability.php/src/Readability.php, line 43
    in /Users/jagermesh/www/reviewlater/vendor/andreskrey/readability.php/src/HTMLParser.php, 147
    in /Users/jagermesh/www/reviewlater/app/HTMLWebParser.php, 28
```

**Comment by andreskrey** [comment]
Hi @jagermesh, sorry for the delay

After investigating this issue I realized that the way I was saving a backup dom for reprocessing the html with different flags (which your page required) had some issues. For some reason the dom and backupdom had a link somehow and after reprocessing the html, the system didn't have a fresh copy of the dom, but a modified one instead. In the page you mentioned, the body tag was missing after the second reprocessing.

I modified the way we store bakcups now (we don't) and created a PR with that. I'm going to close yours. Thanks for the input!

**Comment by jagermesh** [comment]
Great! I will check. What about my last fix for this part
image
did you applied it? I'm using E_ALL and there is notice when there is twitter:image exists but og:image not. I added array_key_exists

**Comment by andreskrey** [comment]
Woops, forgot about that one. Would you mind creating a new PR for that change?

Thanks!

**Comment by andreskrey** [comment]
@jagermesh Sorry for using this old thread to notify you but this is the only (and easiest) way I have to contact you.

Hope you don't mind, but I added you to the [AUTHORS.md file](https://github.com/andreskrey/readability.php/blob/master/AUTHORS.md). Ping me if you want your name removed :)

**Comment by jagermesh** [comment]
Wow, it's a honor. Sure it's ok :)

**Pull request closed without merging**
