### PR TITLE
Added: Configuration parameters array constructor injection

### PR DESCRIPTION
**Pull request by topotru**
Added: Configuration parameters array constructor injection

test added

### CODE REVIEW

**Comment by andreskrey** [comment]
Hi @topotru, would you mind addressing the issues that StyleCI is reporting? I'll do my own reviews meanwhile.

Thanks

**Comment by topotru** [comment]
Done

**Comment by andreskrey** [comment]
@topotru Just added two small comments :)

**Comment by topotru** [comment]
Yeah )

**Comment by topotru** [comment]
Done

**Comment by andreskrey** [comment]
Beautiful, thank you!

**Comment by topotru** [comment]
Thank you! )

**Comment by topotru** [comment]
Don't forget about changelog

**Comment by andreskrey** [comment]
Oh right, thanks

**Comment by topotru** [comment]
Andres, maybe you will make minor release? 
or temporary remove rows 75-82  from readme cause they are not released yet?

**Comment by andreskrey** [comment]
I treat the master branch as the "unreleased" branch but you've made me realized that it can be confusing. I'll do the release tonight. Thanks for the feedback

**Pull request merged**
